TOPDIR = ./../..

REL = keyboard.rel
#LIB=libkeyboard.lib

INCPATH = $(TOPDIR)/include/bstv51
LIBPATH = $(TOPDIR)/libs

CFLAGS = -I$(INCPATH)
LDFLAGS = $(TOPDIR)/src/c51/delay.rel

include $(TOPDIR)/Makefile.env
